### ISSUE TITLE
POC Entwine Rasterization

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-pointcloud#34]
- [x] Read from the Entwine catalog using PDAL Pipeline
- [x] Triangulate using GT Delaunay 
- [x] Rasterize the mesh

NOTE: we don't worry about performance for now.

**Comment by jpolchlo** [comment]
I've created a repository at https://github.com/jpolchlo/pointcloud-dem that tracks this work.  There are some conclusions to be made from having compared the GT triangulation approach to the PDAL one.

The first observation to be made is the comparison between the two triangulators.  GT uses an entirely in-memory approach to triangulation that would be untenable at the very large scales of some point clouds.  This delivers speed at the cost of limited scale.  Whatever triangulator PDAL is relying on will likely make tradeoffs to be able to run at arbitrary scale at the cost of runtime for point sets at the scale that both algorithms can handle.  We see this in our results.

Here are timings for a GT-based TIN to DEM approach operating on 238892 points:
```
Found 21170458 points in EPSG 6348
Loaded pointcloud via PDAL (in 633 ms)
Fetched point data (in 92 ms)
Convert point cloud to array (in 122 ms)
Built triangulation from point set of 238895 points (in 4,552 ms)
Rendered DEM (in 382 ms)
Created GeoTIFF from DEM (in 9 ms)
Wrote GeoTIFF (in 362 ms)
```
The PDAL solution for the same point set yields the following timings:
```
$ time pdal pipeline pdal-dem-pipeline.json 

real	0m49.215s
user	0m42.455s
sys	0m8.406s
```
(Note that the PDAL pipeline is using the null writer in this case.  Writing the PLY file containing the triangulation will account for about 3 seconds extra runtime.)  It's quite obvious that the PDAL triangulator is not viable for any interactive-speed queries, but PDAL is quite capable at funneling point data to GT's triangulator.

The next lesson learned in this process is that we might have to learn how to better customize Entwine hierarchy builds.  The EPT structure that I built (see s3://geotrellis-pointcloud/entwine/USGS_LPC_ME_Eastern_B1_2017_19TEL505083_LAS_2019.ept/) covers a roughly 1500x1500 meter area and uses a "resolution" of 128x128 "cells", with cell count  about 1 point per voxel.  (I'm simplifying out the z-extent of these voxel grids in my thinking because they are much flatter than they are wide.)

For this example, we have a fairly limited scope of resolutions (cell sizes) to pick from.  `1500/(128 * 2^level)` for, in this case, `level=0,...,5`.  (Note that the octree is not complete at every level in general.)  This means square cells of dimension in `{11.719, 5.8594, 2.9297, 1.4648, 0.73242}' are "natural" for this data set.  If we want 1-meter pixels in our DEM, we'd be forced to use level 3, but that would imply also loading all the points in levels 0, 1, and 2, over all voxel grids, which would add up to about 5.9 million points, which will not triangulate in a reasonable time for an interactive query (this triangulation, based on past experience would take minutes to return).  The 1 point per pixel heuristic already implies a need for over 2 million points, which will not be an interactive query as it is.

We are going to have to put some thought into how we will build our EPT hierarchies so that we can meet the demands of typical users.  We should pick the span (the power of two number of cells to divide the initial volume and all octree nodes) to allow the point clouds to fit well into the layout that DEM requests are likely to appear in.  But we are also likely to want to have larger cell sizes for the point data than the pixel data.  The loss of fidelity is likely to be small.  Consider the difference between the following two images:

![dem](https://user-images.githubusercontent.com/18410961/75396731-3dfbca80-58c3-11ea-928f-746c5caa6194.png)
![dem-coarse](https://user-images.githubusercontent.com/18410961/75396742-4227e800-58c3-11ea-88df-1bdf4e6d00a5.png)

These are the same area, the first rendered using 230k points, the second using 33k points.  The timings were 4s to triangulate the first, 0.9s for the latter.  Depending on application, the latter, cheaper image would be quite satisfactory.

Of course, tuning the EPT hierarchy to the application should net even better results.

**Comment by jpolchlo** [comment]
My last comments require amendments.  It turns out that I was using a PDAL build that is somehow _not quite right_, and the performance I was seeing from PDAL wasn't representative of what should be expected.  In reality, PDAL performs roughly twice as fast as the GT triangulator.

That said, PDAL's triangulator is not nearly as sophisticated as I assumed, and the triangluation appears to be performed in-memory, so very large triangulations will likely fail (as they would for GT, though GT has some facilities for distributing the workload, with some caveats regarding correctness).

All other comments regarding the EPT hierarchies still apply.
