### ISSUE TITLE
EPTMetadata produces too many reads for large catalogs

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-pointcloud#60]
During `DEMRasterSource` initialization we end up in `EPTMetadata.pointsIntLevel`

https://github.com/geotrellis/geotrellis-pointcloud/blob/71953977dd75357dbab3ca6a89cf3bea1d20111a/pointcloud/src/main/scala/geotrellis/pointcloud/raster/ept/EPTMetadata.scala#L43-L54

This appears to want to read metadata for every tile which is not practical for large catlogs

Example:
```scala
scala> import geotrellis.pointcloud.raster.ept._
import geotrellis.pointcloud.raster.ept._

scala> EPTMetadata("s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/").extent
```

Once instrumented stalls out:

```
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 0-0-0-0
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-187-13-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-117-92-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-194-196-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-164-154-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-157-145-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-160-162-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-189-65-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-205-226-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-176-207-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-105-163-128
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-136-103-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-65-110-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-142-253-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-168-206-127
Reading: s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/ -- 8-130-177-127
...
```

the core issue is to have reasonable start-up for large catalogs from 3DEP program. I'm not sure if we need to sample the metadata or perhaps there are some aggregate metadata available in EPT structure.

**Comment by pomadchin** [comment]
We can simplify it: we don't need to parse all the files now (nothing from it is used except CRS and Extent). 

There are two possible options:
1. read and parse _only_ ept.json file ourselves 
2. add a [stats filter](https://pdal.io/stages/filters.stats.html) into the pipeline and read metadata via PDAL and parse its metadata.

**Comment by jpolchlo** [comment]
Option 1: we already do this.

Option 2, not so much:
```
$ pdal info --stats --driver readers.ept s3://usgs-lidar-public/USGS_LPC_NY_Cl_Ess_LChamp_P2_2014_LAS_2016/
(pdal info readers.ept Warning) 64941342868 will be downloaded
```
The operation did not return in sufficient time.  (Nor do I think it does what we want.)

Note that we're hanging up trying to determine the depth of the hierarchy so that we can calculate the resolutions.  This requires reading into the `ept-hierarchy` files.  In the case of the specific test file, there are 37k+ tree nodes, 30k+ of which require reading an additional file.  There's no way to know by quick inspection how deep the tree goes, since one of these subordinate hierarchy files can go arbitrarily deep.  It's also not part of the `ept.json`. 

Without a faster method of discovering the tree depth, we're either stuck with the complete read method (BAD; in this case requiring 30k+ reads to get the depth), or we'll have to guess about the depth of the tree.  We might also attempt to sample some of these files, but we may miss the true depth of the tree in this fashion.
